/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.kamil.ociepa.projektpoferiowy;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author a20ko
 */
public class UlubioneAnime extends javax.swing.JFrame {

    /**
     * Creates new form UlubioneAnime
     */
    public UlubioneAnime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ko_jPanelGlowny = new javax.swing.JPanel();
        ko_jLabelAnime = new javax.swing.JLabel();
        ko_jLabelImie = new javax.swing.JLabel();
        ko_jLabelNazwisko = new javax.swing.JLabel();
        ko_jLabelWiek = new javax.swing.JLabel();
        ko_jLabelUlubioneAnime = new javax.swing.JLabel();
        ko_jSliderWiek = new javax.swing.JSlider();
        ko_jTextFieldImie = new javax.swing.JTextField();
        ko_jTextFieldNazwisko = new javax.swing.JTextField();
        ko_jComboBoxAnime = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ko_jTextAreaOpis = new javax.swing.JTextArea();
        ko_jLabelOpis = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ko_jMenuPlik = new javax.swing.JMenu();
        ko_jMenuItemZapisz = new javax.swing.JMenuItem();
        ko_jMenuItemEdycja = new javax.swing.JMenuItem();
        ko_jMenuItemZamknij = new javax.swing.JMenuItem();
        ko_jMenuEdycja = new javax.swing.JMenu();
        ko_jMenuItemCzcionka = new javax.swing.JMenuItem();
        ko_jMenuItemTlo = new javax.swing.JMenuItem();
        ko_jMenuOprogramie = new javax.swing.JMenu();
        ko_jMenuItemOprogramie = new javax.swing.JMenuItem();
        ko_jMenuItemPomoc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Twoje ulubione anime");
        setBackground(new java.awt.Color(255, 204, 204));

        ko_jPanelGlowny.setBackground(new java.awt.Color(255, 204, 204));
        ko_jPanelGlowny.setForeground(new java.awt.Color(255, 255, 255));

        ko_jLabelAnime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ko_jLabelAnime.setText("Jakie anime lubisz?");

        ko_jLabelImie.setText("Imię:");

        ko_jLabelNazwisko.setText("Nazwisko:");

        ko_jLabelWiek.setText("Wiek:");

        ko_jLabelUlubioneAnime.setText("Anime:");

        ko_jSliderWiek.setMajorTickSpacing(5);
        ko_jSliderWiek.setMinorTickSpacing(1);
        ko_jSliderWiek.setPaintLabels(true);
        ko_jSliderWiek.setPaintTicks(true);
        ko_jSliderWiek.setSnapToTicks(true);

        ko_jTextFieldImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jTextFieldImieActionPerformed(evt);
            }
        });

        ko_jComboBoxAnime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hunter x Hunter", "Haikyuu", "Naruto", "One Piece", "Sailor Moon", "SK8 The Infinity", "Dr Stone", "Death Note", " " }));

        ko_jTextAreaOpis.setColumns(20);
        ko_jTextAreaOpis.setRows(5);
        jScrollPane1.setViewportView(ko_jTextAreaOpis);

        ko_jLabelOpis.setText("Tutaj możesz napisać o swoim ulubionym anime:");

        javax.swing.GroupLayout ko_jPanelGlownyLayout = new javax.swing.GroupLayout(ko_jPanelGlowny);
        ko_jPanelGlowny.setLayout(ko_jPanelGlownyLayout);
        ko_jPanelGlownyLayout.setHorizontalGroup(
            ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                                .addComponent(ko_jLabelWiek)
                                .addGap(27, 27, 27)
                                .addComponent(ko_jSliderWiek, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                                .addComponent(ko_jLabelUlubioneAnime)
                                .addGap(18, 18, 18)
                                .addComponent(ko_jComboBoxAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ko_jLabelNazwisko)
                                    .addComponent(ko_jLabelImie))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ko_jTextFieldNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(ko_jTextFieldImie)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ko_jLabelOpis)))
                    .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(ko_jLabelAnime)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        ko_jPanelGlownyLayout.setVerticalGroup(
            ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelGlownyLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ko_jLabelAnime)
                .addGap(47, 47, 47)
                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelImie)
                    .addComponent(ko_jTextFieldImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelNazwisko)
                    .addComponent(ko_jTextFieldNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelWiek)
                    .addComponent(ko_jSliderWiek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(ko_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelUlubioneAnime)
                    .addComponent(ko_jComboBoxAnime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(ko_jLabelOpis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        ko_jMenuPlik.setText("Plik");

        ko_jMenuItemZapisz.setText("Zapisz");
        ko_jMenuItemZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemZapiszActionPerformed(evt);
            }
        });
        ko_jMenuPlik.add(ko_jMenuItemZapisz);

        ko_jMenuItemEdycja.setText("Wczytaj");
        ko_jMenuPlik.add(ko_jMenuItemEdycja);

        ko_jMenuItemZamknij.setText("Zamknij");
        ko_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemZamknijActionPerformed(evt);
            }
        });
        ko_jMenuPlik.add(ko_jMenuItemZamknij);

        jMenuBar1.add(ko_jMenuPlik);

        ko_jMenuEdycja.setText("Edycja");

        ko_jMenuItemCzcionka.setText("Zmień czcionkę");
        ko_jMenuEdycja.add(ko_jMenuItemCzcionka);

        ko_jMenuItemTlo.setText("Zmień tło (pomarańczowy)");
        ko_jMenuItemTlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemTloActionPerformed(evt);
            }
        });
        ko_jMenuEdycja.add(ko_jMenuItemTlo);

        jMenuBar1.add(ko_jMenuEdycja);

        ko_jMenuOprogramie.setText("O programie");

        ko_jMenuItemOprogramie.setText("O programie");
        ko_jMenuOprogramie.add(ko_jMenuItemOprogramie);

        ko_jMenuItemPomoc.setText("Pomoc");
        ko_jMenuOprogramie.add(ko_jMenuItemPomoc);

        jMenuBar1.add(ko_jMenuOprogramie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ko_jPanelGlowny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ko_jPanelGlowny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ko_jTextFieldImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jTextFieldImieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ko_jTextFieldImieActionPerformed

    private void ko_jMenuItemZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemZapiszActionPerformed
        String imie = ko_jTextFieldImie.getText();
        String nazwisko = ko_jTextFieldNazwisko.getText();
        int wiek = ko_jSliderWiek.getValue();
        String anime = (String) ko_jComboBoxAnime.getSelectedItem();
        String opis = ko_jTextAreaOpis.getText();
        
        String cale = (""+imie+"; "+nazwisko+"; "+ wiek+"; " +anime+"; "+opis+";");
        
        File f = new File(imie+"_"+nazwisko+".txt");        
        try{
                   
            FileWriter fw = new FileWriter(f);
            fw.write(cale);
            fw.close();
        } catch(IOException e){
            System.out.println("błąd: "+e.toString());
        }
    }//GEN-LAST:event_ko_jMenuItemZapiszActionPerformed

    private void ko_jMenuItemTloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemTloActionPerformed
        ko_jPanelGlowny.setBackground(Color.orange);
    }//GEN-LAST:event_ko_jMenuItemTloActionPerformed

    private void ko_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ko_jMenuItemZamknijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UlubioneAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UlubioneAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UlubioneAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UlubioneAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UlubioneAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ko_jComboBoxAnime;
    private javax.swing.JLabel ko_jLabelAnime;
    private javax.swing.JLabel ko_jLabelImie;
    private javax.swing.JLabel ko_jLabelNazwisko;
    private javax.swing.JLabel ko_jLabelOpis;
    private javax.swing.JLabel ko_jLabelUlubioneAnime;
    private javax.swing.JLabel ko_jLabelWiek;
    private javax.swing.JMenu ko_jMenuEdycja;
    private javax.swing.JMenuItem ko_jMenuItemCzcionka;
    private javax.swing.JMenuItem ko_jMenuItemEdycja;
    private javax.swing.JMenuItem ko_jMenuItemOprogramie;
    private javax.swing.JMenuItem ko_jMenuItemPomoc;
    private javax.swing.JMenuItem ko_jMenuItemTlo;
    private javax.swing.JMenuItem ko_jMenuItemZamknij;
    private javax.swing.JMenuItem ko_jMenuItemZapisz;
    private javax.swing.JMenu ko_jMenuOprogramie;
    private javax.swing.JMenu ko_jMenuPlik;
    private javax.swing.JPanel ko_jPanelGlowny;
    private javax.swing.JSlider ko_jSliderWiek;
    private javax.swing.JTextArea ko_jTextAreaOpis;
    private javax.swing.JTextField ko_jTextFieldImie;
    private javax.swing.JTextField ko_jTextFieldNazwisko;
    // End of variables declaration//GEN-END:variables
}
